@startuml
title Citizen Intelligence Agency System - Web Application - Components
caption Web
package WebApplication {
  component "AgencyDAO" <<Spring Repository>> as 44
  component "AgentContainer" <<Spring Component>> as 37
  component "ApplicationActionEventDAO" <<Spring Repository>> as 55
  component "ApplicationConfigurationDAO" <<Spring Repository>> as 48
  component "ApplicationConfigurationService" <<Spring Service>> as 31
  component "ApplicationManager" <<Spring Service>> as 16
  component "ApplicationSessionDAO" <<Spring Repository>> as 54
  component "AuthenticationProvider" <<Spring Component>> as 36
  component "BootstrapDefaultConfig" <<Spring Component>> as 38
  component "CommitteeProposalComponentDataDAO" <<Spring Repository>> as 59
  component "ConfigurationManager" <<Spring Service>> as 29
  component "CountryElementDAO" <<Spring Repository>> as 52
  component "CreateApplicationEventService" <<Spring Service>> as 32
  component "CreateApplicationSessionService" <<Spring Service>> as 15
  component "DataContainer" <<Spring Component>> as 39
  component "DataDAO" <<Spring Repository>> as 47
  component "DataViewer" <<Spring Repository>> as 50
  component "DestroyApplicationSessionService" <<Spring Service>> as 27
  component "DisableGoogleAuthenticatorCredentialService" <<Spring Service>> as 20
  component "DocumentContentDataDAO" <<Spring Repository>> as 51
  component "DocumentElementDAO" <<Spring Repository>> as 43
  component "DocumentStatusContainerDAO" <<Spring Repository>> as 61
  component "DocumentWordCountService" <<Spring Service>> as 33
  component "EmailService" <<Spring Component>> as 35
  component "IndicatorElementDAO" <<Spring Repository>> as 60
  component "JobContextHolder" <<Spring Service>> as 11
  component "LanguageContentDataDAO" <<Spring Repository>> as 57
  component "LanguageContentService" <<Spring Service>> as 28
  component "LanguageDataDAO" <<Spring Repository>> as 53
  component "LoginBlockedAccess" <<Spring Service>> as 22
  component "LoginService" <<Spring Service>> as 13
  component "LogoutService" <<Spring Service>> as 17
  component "PersonDataDAO" <<Spring Repository>> as 49
  component "RefreshDataViewsService" <<Spring Service>> as 30
  component "RegisterUserService" <<Spring Service>> as 25
  component "RemoveDataManager" <<Spring Service>> as 21
  component "RemoveDataService" <<Spring Service>> as 18
  component "SearchDocumentService" <<Spring Service>> as 26
  component "SearchIndexer" <<Spring Repository>> as 42
  component "SendEmailService" <<Spring Service>> as 23
  component "SetGoogleAuthenticatorCredentialService" <<Spring Service>> as 14
  component "SwedenPoliticalPartyDAO" <<Spring Repository>> as 58
  component "UpdateApplicationConfigurationService" <<Spring Service>> as 19
  component "UpdateSearchIndexService" <<Spring Service>> as 10
  component "UserDAO" <<Spring Repository>> as 46
  component "ViewDataDataContainerFactory" <<Spring Component>> as 34
  component "ViewDataManager" <<Spring Service>> as 12
  component "ViewRiksdagenCommitteeDAO" <<Spring Repository>> as 56
  component "ViewRiksdagenMinistryDAO" <<Spring Repository>> as 45
  component "VoteDataDAO" <<Spring Repository>> as 41
  component "WordCounter" <<Spring Service>> as 24
}
31 ..> 48 
16 ..> 37 
16 ..> 39 
16 ..> 34 
38 ..> 29 
29 ..> 44 
29 ..> 53 
32 ..> 54 
15 ..> 54 
39 ..> 59 
39 ..> 51 
39 ..> 43 
39 ..> 61 
39 ..> 49 
39 ..> 41 
27 ..> 54 
20 ..> 46 
33 ..> 51 
33 ..> 24 
35 ..> 31 
11 ..> 42 
11 ..> 12 
28 ..> 57 
22 ..> 55 
22 ..> 31 
22 ..> 54 
22 ..> 46 
13 ..> 22 
13 ..> 46 
30 ..> 12 
25 ..> 31 
25 ..> 46 
18 ..> 21 
26 ..> 51 
26 ..> 43 
23 ..> 35 
14 ..> 44 
14 ..> 46 
19 ..> 48 
10 ..> 42 
34 ..> 39 
34 ..> 50 
@enduml