@startuml
title Citizen Intelligence Agency System - Deployment
caption Deployment Aws.
node "Application (x2)" <<EC2>> as 110 {
  artifact "Web Application" <<Container>> as 111
}
node "Application Loadbalancer" <<ALB>> as 108 {
  artifact "Loadbalancer" <<Container>> as 109
}
node "Database (x2)" <<RDS>> as 114 {
  artifact "Database" <<Container>> as 115
}
109 ..> 111 : HTTPS/H2
111 ..> 115 : JDBC
@enduml